### ISSUE TITLE
how to run this project 

### ISSUE THREAD

**Issue by Jaswanth2323** [MoriKeli/Instagram_clone#7]

**Comment by morikeli** [comment]
### Project setup

**NOTE**: Make sureyou have installed Python on your machine.

$ cd Desktop
  $ git clone https://github.com/morikeli/Instagram_clone.git
  $ python3 -m venv .instagram-clone-venv
  $ source .instagram-clone-venv/bin/activate
  $ pip install -r requirements.txt

Once all packages are installed. You can access the website on your localhost by typing `python manage.py runserver`

Access website using this url:

`127.0.0.1:8000/accounts/login/`
